name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker asia-southeast2-docker.pkg.dev

    - name: Build and Push Docker Image
      run: |
        IMAGE=asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_REPO }}/${{ secrets.CLOUD_RUN_SERVICE }}:${{ github.sha }}
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Deploy to Cloud Run
      run: |
        IMAGE=asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_REPO }}/${{ secrets.CLOUD_RUN_SERVICE }}:${{ github.sha }}
        gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
          --image $IMAGE \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated \
          --memory 1Gi \
          --timeout 900s
